"""empty message

Revision ID: deb7036a6019
Revises: 
Create Date: 2026-03-14 17:48:11.146113

"""
from datetime import datetime

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'deb7036a6019'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('date_joined', sa.DateTime(), server_default=str(datetime.now().date()), nullable=True))
        batch_op.add_column(sa.Column('pronouns', sa.String(length=25), nullable=True))
        batch_op.add_column(sa.Column('description', sa.String(length=500), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('description')
        batch_op.drop_column('pronouns')
        batch_op.drop_column('date_joined')

    # ### end Alembic commands ###
